version: '2'
services:
    selenium-hub:
      image: selenium/hub
      ports:
        - "4444:4444"
      networks:
        - all

    firefox:
        image: selenium/node-firefox
        environment:
          - "HUB_PORT_4444_TCP_ADDR=selenium-hub"
          - "HUB_PORT_4444_TCP_PORT=4444"
          - "SE_OPTS=-browser browserName=firefox,version=40.0b3,maxInstances=3,platform=LINUX"
        links:
          - selenium-hub
        networks:
          - all
networks:
  all: